name: radar_diagram
description: "A customizable charts radar(spider) charts. Easily visualize multivariate data with interactive and beautiful radar diagrams."
version: 1.0.0
repository: https://github.com/GoltVik/radar_diagram

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

